obstacle_range: 2.0
raytrace_range: 3.0
# footprint: [[0.10, 0.10], [0.10, -0.10], [-0.10, -0.10], [-0.10, 0.10]]
# footprint_inflation: 0.01
robot_radius: 0.025
inflation_radius: 0.20
max_obstacle_height: 0.4
min_obstacle_height: 0.2

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}