TebLocalPlannerROS:
  odom_topic: odom

  # Trajectory

  # 优化期间允许改变轨迹的时域长度
  teb_autosize: True
  # 局部路径规划的解析度
  dt_ref: 0.3
  # 允许改变的时域解析度的浮动范围，一般为 dt_ref 的 10% 左右;
  dt_hysteresis: 0.1
  # 最大样本数
  max_samples: 500
  # 覆盖全局路径中局部路径点的朝向
  global_plan_overwrite_orientation: True
  # 允许在开始时想后退来执行轨迹
  allow_init_with_backwards_motion: False
  # 考虑优化的全局计划子集的最大长度（累积欧几里得距离）
  # 如果为0或负数：禁用；长度也受本地Costmap大小的限制
  max_global_plan_lookahead_dist: 3.0
  # 从全局路径中选取的每两个连续通过点之间的最小间隔
  global_plan_viapoint_sep: -1
  # 该参数决定了从机器人当前位置的后面一定距离开始裁剪
  global_plan_prune_distance: 1
  # 如果为真，规划器在速度、加速度和转弯率计算中使用精确的弧长[增加的CPU时间]，否则使用欧几里德近似。
  exact_arc_length: False
  # 若3个点均不发生碰撞，则认为本次轨迹有效。若小于0则检查所有路径点
  # 检测位姿可到达的时间间隔
  feasibility_check_no_poses: 5
  # 发布包含完整轨迹和活动障碍物列表的规划器反馈
  publish_feedback: False

  # Robot
  # 最大x前线速度
  max_vel_x: 0.4
  # 最大x后退速度
  max_vel_x_backwards: 0.2
  # 最大y方向速度
  max_vel_y: 0.0
  # 最大转向角速度
  max_vel_theta: 0.5
  # 最大x加速度
  acc_lim_x: 0.5
  # 最大角加速度
  acc_lim_theta: 0.5
  # 车类机器人的最小转弯半径
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: "point"

  # GoalTolerance
  # 目标xy偏移容忍度
  xy_goal_tolerance: 0.2
  # 目标角度偏移容忍度
  yaw_goal_tolerance: 0.1
  # 允许机器人以最大速度驶向目的地，为False时，车到达终点时的目标速度为0；
  free_goal_vel: True
  complete_global_plan: True

  # Obstacles
  # 和障碍物最小距离
  min_obstacle_dist: 0.2 # This value must also include our robot radius, since footprint_model is set to "point".
  # 障碍物膨胀距离
  inflation_dist: 0.6
  # costmap中的障碍物是否被直接考虑
  include_costmap_obstacles: True
  # 规划时考虑后面n米内的障碍物
  costmap_obstacles_behind_robot_dist: 1.0
  # 障碍物姿态受影响程度0-30
  obstacle_poses_affected: 15

  # 动态障碍物的膨胀范围
  dynamic_obstacle_inflation_dist: 0.6
  # 是否将动态障碍物预测为速度模型
  include_dynamic_obstacles: True

  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # Optimization
  # 每次外部循环迭代中调用的实际求解器迭代次数
  no_inner_iterations: 5
  # 每次外部循环迭代都会根据所需的时间分辨率dt_ref自动调整轨迹的大小，并调用内部优化器（执行no_inner_iterations）
  # 因此，每个计划周期中求解程序迭代的总数是两个值的乘积
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  # 为惩罚函数增加一个小的安全余量，以实现硬约束近似
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  # 满足最大允许平移速度的优化权重
  weight_max_vel_x: 2
  # 满足最大允许角速度的优化权重
  weight_max_vel_theta: 1
  # 满足最大允许平移加速度的优化权重
  weight_acc_lim_x: 1
  # 满足最大允许角加速度的优化重量
  weight_acc_lim_theta: 1
  # 以便在顺应性纵向运动与不顺应性横向运动（分层）之间进行权衡
  weight_kinematics_nh: 1000
  # 优化权重，迫使机器人仅选择前进方向（正向速度）。较小的权重（例如1.0）仍然允许向后行驶
  weight_kinematics_forward_drive: 1
  # 优化权重，以实现最小转弯半径（仅适用于汽车类机器人）。
  weight_kinematics_turning_radius: 1
  # 胆子 根据转换/执行时间对轨迹进行收缩的优化权重
  weight_optimaltime: 30 # must be > 0
  weight_shortest_path: 0
  # 优化权重以保持与障碍物的最小距离
  weight_obstacle: 100
  # 通胀惩罚的优化权重（应该很小）
  weight_inflation: 0.2
  weight_dynamic_obstacle: 10
  weight_dynamic_obstacle_inflation: 0.2
  # 跟踪全据路径的权重
  weight_viapoint: 1
  weight_adapt_factor: 2

  # Homotopy Class Planner

  # 激活并行规划
  enable_homotopy_class_planning: True
  # 激活多个线程，以便在不同的线程中规划每个轨迹
  enable_multithreading: True
  # 考虑到的不同轨迹的最大数量
  max_number_classes: 4
  # 轨迹成本
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  # 障碍物成本
  selection_obst_cost_scale: 100.0
  # 如果为真，时间成本(时间差平方和)被总转移时间(时间差和)所替代
  selection_alternative_time_cost: False
  # 指定为创建路线图而生成的样本数
  roadmap_graph_no_samples: 15
  # 指定该区域的宽度
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  #（0.2 < value <= 1）缩放用于区分同伦类的内部参数（H-signature）
  h_signature_prescaler: 0.5
  # 如果实部和复部的差都低于规定的阈值，则假定两个h签名相等
  h_signature_threshold: 0.1
  # 指定障碍目标头和目标标头之间的标量积的值，以便将(障碍)考虑到勘探中
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  # 如果为真，则不同拓扑的所有轨迹都附加到这组vio -points上，否则只有共享与初始/全局计划相同拓扑的轨迹与它们连接
  viapoints_all_candidates: True
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  # 可视化创建的图形，用于探索不同的轨迹（在rviz中检查标记消息）
  visualize_hc_graph: False

  visualize_with_time_as_z_axis_scale: False

  # Recovery

  # 允许规划器在自动检测到问题的情况下临时缩小horizon（50％）
  shrink_horizon_backup: True
  # 指定最低持续时间减少地平线以备不可行轨迹检测
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
